import { C } from "./theme.js";

export const SEED = [
  {
    id: "walmart",
    tier: "enterprise",
    customer: "Walmart Supplier Academy",
    org: "Walmart",
    useCase: "Self-service AI localization of Supplier Academy L&D to launch non-English markets.",
    goLive: "Early August · fr-CA first wave",
    contentPath: "e-Learning", maturity: "greenfield", delivery: "manual",
    reviewModel: "internal",          // "reviewers by market", Ryan on CA — their own people
    specialization: "Retail & e-commerce",
    industry: "Retail / supply chain",
    fde: "Paul Sanabria", segment: "NA Enterprise",
    team: ["kat", "phil", "paul", "ryan", "james"],
    updated: "Jul 13", stage: "core", stageProgress: 0.35,
    startDate: "2026-06-24", goLiveDate: "2026-08-07", lastActivityDate: "2026-07-13", ownerName: "Kat",
    health: [0, 0, 20, 0, 45, 60, 0, 0, 0, 0, 0, 0, 0],
    nudge: "You're on the fr-CA legal path. Your first SCORM file is through end-to-end — running the remaining Grow with Walmart Canada courses unlocks UAT sign-off. One blocker: the glossary and style guide is still pending from Phillip, which is holding the Linguistic Assets step.",
    notes: {},
  },
  {
    id: "thermo",
    tier: "enterprise",
    customer: "Thermo Fisher HID",
    org: "Thermo Fisher",
    useCase: "Replace a manual, email-driven handoff between marketing and regional reviewers.",
    goLive: "Live since Apr 2026",
    contentPath: "Document & text", maturity: "mature",
    fde: "Gagan Reddy", segment: "NA Enterprise",
    team: ["nicki", "jackie", "paul"],
    updated: "Jul 2", stage: "hyper", stageProgress: 1,
    startDate: "2026-02-02", goLiveDate: "2026-04-10", lastActivityDate: "2026-07-02", ownerName: "Nicki",
    health: [92, 71, 88, 44, 96, 90, 92, 92, 92, 92, 92, 92, 92],
    nudge: "Hypercare closed clean — every health target is met. Nicki is the reference candidate for the next HID business unit; the before/after workflow numbers are the strongest asset you have.",
    notes: {},
  },
  {
    id: "thermo-chrom",
    tier: "enterprise",
    customer: "Thermo Fisher · Chromatography",
    org: "Thermo Fisher",
    useCase: "Second business unit adopting the pipeline HID already proved out.",
    goLive: "Oct 2026 target",
    contentPath: "Document & text", maturity: "mature",
    fde: "Gagan Reddy", segment: "NA Enterprise",
    team: ["jackie", "paul"],
    updated: "Jul 24", stage: "kickoff", stageProgress: 0.5,
    startDate: "2026-07-14", goLiveDate: "2026-10-09", lastActivityDate: "2026-07-24", ownerName: "Priya",
    health: [88, 64, 82, 30, 40, 45, 88, 88, 88, 88, 88, 88, 88],
    inheritedFrom: {
      id: "thermo",
      customer: "Thermo Fisher HID",
      carries: ["Workspace & project templates", "AI translation profile", "TMX + termbase", "Reviewer roster", "Locale set"],
    },
    notes: {},
  },
  {
    id: "wholesome",
    tier: "enterprise",
    customer: "Wholesome Goods",
    org: "Wholesome Goods",
    useCase: "Stand up 13 EU regional storefronts on one shared translation pipeline.",
    goLive: "Phased · aligned to Feb 2027 renewal",
    contentPath: "Document & text", maturity: "mature", delivery: "connected", connector: "Sitecore",
    reviewModel: "internal",          // "regional marketing leads review"
    specialization: "Retail & e-commerce",
    industry: "Consumer goods",
    fde: "Gagan Reddy", segment: "EMEA Enterprise",
    team: ["sam", "jackie", "paul"],
    updated: "Jul 22", stage: "uat", stageProgress: 0.5,
    startDate: "2026-04-06", goLiveDate: "2026-09-30", lastActivityDate: "2026-07-22", ownerName: "Samantha",
    health: [78, 46, 64, 12, 71, 74, 78, 78, 78, 78, 78, 78, 78],
    nudge: "Eleven of thirteen regions have passed a real end-to-end run. Before go-live, the two remaining regions need reviewers assigned — and reviewer-agent usage is the one health metric still short of target.",
    notes: {},
  },
  {
    id: "stepstone",
    tier: "teams",
    customer: "StepStone",
    org: "StepStone",
    useCase: "Give recruiting teams a self-serve path for job content instead of a ticket queue.",
    goLive: "Sept 2026 target",
    contentPath: "Document & text", maturity: "mature",
    reviewModel: "internal",
    specialization: "HR & training",
    industry: "Recruitment",
    fde: "Gagan Reddy", segment: "EMEA Enterprise",
    team: ["kelli", "jackie"],
    updated: "Jul 19", stage: "session1", stageProgress: 0.6,
    startDate: "2026-06-15", goLiveDate: "2026-09-30", lastActivityDate: "2026-07-19", ownerName: "Kelli",
    health: [34, 18, 40, 0, 22, 55, 34, 34, 34, 34, 34, 34, 34],
    nudge: "Workspace is provisioned and templates are half-built. The fastest unlock is the assignment template for recruiter self-serve — everything downstream in the core path waits on it.",
    notes: {},
  },
  {
    id: "sbd",
    tier: "enterprise",
    customer: "Stanley Black & Decker",
    org: "Stanley Black & Decker",
    useCase: "Localize product training video for 18 regional workspaces on a shared template.",
    goLive: "Live since Jun 2026",
    contentPath: "Video & audio", maturity: "mature",
    fde: "Gagan Reddy", segment: "Global Enterprise",
    team: ["jackie", "paul", "james"],
    updated: "Jun 28", stage: "hyper", stageProgress: 1,
    startDate: "2026-03-02", goLiveDate: "2026-06-15", lastActivityDate: "2026-06-28", ownerName: "Jackie",
    health: [85, 52, 94, 38, 91, 83, 85, 85, 85, 85, 85, 85, 85],
    nudge: "All 18 workspaces are live on the shared template. Subtitle turnaround is the metric worth quoting in the renewal conversation.",
    notes: {},
  },
];

/* ────────────────────────────────────────────────────────────
   Journey assembly
   ──────────────────────────────────────────────────────────── */
