import { C } from "./theme.js";

export const SEED = [
  {
    id: "walmart",
    customer: "Walmart Supplier Academy",
    org: "Walmart",
    useCase: "Self-service AI localization of Supplier Academy L&D to launch non-English markets.",
    goLive: "Early August · fr-CA first wave",
    contentPath: "e-Learning", maturity: "greenfield", delivery: "manual",
    reviewModel: "internal",          // "reviewers by market", Ryan on CA — their own people
    specialization: "Retail & e-commerce",
    industry: "Retail / supply chain",
    fde: "Paul Sanabria", segment: "NA Enterprise",
    team: ["kat", "phil", "paul", "ryan", "james"],
    updated: "Jul 13", stage: "core", stageProgress: 0.35,
    startDate: "2026-06-24", goLiveDate: "2026-08-07", lastActivityDate: "2026-07-13", ownerName: "Kat",
    health: [0, 0, 20, 0, 45, 60],
    nudge: "You're on the fr-CA legal path. Your first SCORM file is through end-to-end — running the remaining Grow with Walmart Canada courses unlocks UAT sign-off. One blocker: the glossary and style guide is still pending from Phillip, which is holding the Linguistic Assets step.",
    notes: {
      goals: "Self-service AI localization of Supplier Academy L&D to launch non-English markets.",
      content: "SCORM out of Rise + Storyline; audio/video, images.",
      langs: "Source en-US. fr-CA first (legal), then es-MX, es-CL, hi-IN, zh.",
      who: "Kat lead; Phillip & Cody (content/ID); reviewers by market.",
      welcome: "Success = speed to market, on-time delivery, quality.",
      cadence: "Next session Mon 1:00 PM ET.",
      provision: "'Walmart Supplier Academy' provisioned; team logged in.",
      smartwords: "2.2M smartwords; extra gifted for onboarding tests.",
      sso: "Out of scope — email/password login.",
      templates: "AI translation, SME review, language/legal review.",
      aiprofile: "Covered in upcoming technical setup calls.",
      workflow: "AI translation already run on samples.",
      a2: "Pending from Phillip.",
      e2e: "Paul ran full E2E workflow.",
      accept: "Sign-off gate.",
      signoff: "Sign-off gate.",
      am: "Staying with James Willson.",
    },
    markers: [
      {
        id: "m-wm-1", after: "kickoff", kind: "decision",
        text: "fr-CA goes first because of Quebec legal requirements — es-MX and the rest follow",
        at: "2026-07-02",
      },
      {
        id: "m-wm-2", after: "setup", kind: "note",
        text: "SSO ruled out of scope for this phase; email and password login for now",
        at: "2026-07-09",
      },
    ],
    tickets: [
      {
        id: "t-wm-1", stepKey: "a2", state: "waiting", owner: "phil", ref: "SUP-4821",
        text: "Glossary and style guide not started — waiting on terminology sign-off from the merchandising team",
        at: "2026-07-08",
      },
    ],
    dueDates: {
      a2: "2026-07-10",        // glossary from Phillip — the blocker, now well past
      templates: "2026-07-29",
      c4: "2026-08-03",
      e2e: "2026-07-31",
    },
    explicit: {
      goals: "done", content: "done", langs: "done", assets: "open", who: "done",
      welcome: "done", "3pvm": "open", path: "done", cadence: "active",
      provision: "done", smartwords: "done", sso: "done", templates: "active", aiprofile: "active",
      users: "open", projects: "open", workflow: "active", a1: "open", a2: "open", a3: "open",
      review: "open", reporting: "open",
      c1: "done", c2: "done", c3: "done", c4: "open", c5: "open",
      e2e: "done", quality: "open", selfrun: "done", accept: "open",
      health: "open", reports: "open", signoff: "open",
      am: "na", support: "open", recheck: "open",
    },
  },
  {
    id: "thermo",
    customer: "Thermo Fisher HID",
    org: "Thermo Fisher",
    useCase: "Replace a manual, email-driven handoff between marketing and regional reviewers.",
    goLive: "Live since Apr 2026",
    contentPath: "Document & text", maturity: "mature",
    fde: "Gagan Reddy", segment: "NA Enterprise",
    team: ["nicki", "jackie", "paul"],
    updated: "Jul 2", stage: "hyper", stageProgress: 1,
    startDate: "2026-02-02", goLiveDate: "2026-04-10", lastActivityDate: "2026-07-02", ownerName: "Nicki",
    health: [92, 71, 88, 44, 96, 90],
    nudge: "Hypercare closed clean — every health target is met. Nicki is the reference candidate for the next HID business unit; the before/after workflow numbers are the strongest asset you have.",
    notes: {
      goals: "Cut the manual review loop; regional teams were routing files by email.",
      langs: "en-US source into de-DE, fr-FR, ja-JP, zh-CN.",
      assets: "TMX + termbase inherited from prior LSP.",
      workflow: "Full end-to-end running in production.",
      am: "Jackie Stanforth owns the account.",
    },
  },
  {
    id: "thermo-chrom",
    customer: "Thermo Fisher · Chromatography",
    org: "Thermo Fisher",
    useCase: "Second business unit adopting the pipeline HID already proved out.",
    goLive: "Oct 2026 target",
    contentPath: "Document & text", maturity: "mature",
    fde: "Gagan Reddy", segment: "NA Enterprise",
    team: ["jackie", "paul"],
    updated: "Jul 24", stage: "kickoff", stageProgress: 0.5,
    startDate: "2026-07-14", goLiveDate: "2026-10-09", lastActivityDate: "2026-07-24", ownerName: "Priya",
    health: [88, 64, 82, 30, 40, 45],
    inheritedFrom: {
      id: "thermo",
      customer: "Thermo Fisher HID",
      carries: ["Workspace & project templates", "AI translation profile", "TMX + termbase", "Reviewer roster", "Locale set"],
    },
    notes: {
      goals: "Same pipeline as HID, scoped to chromatography product content.",
      langs: "en-US into de-DE, fr-FR, ja-JP — matching the HID locale set.",
      who: "Priya leads; HID's reviewers cover the shared locales.",
    },
  },
  {
    id: "wholesome",
    customer: "Wholesome Goods",
    org: "Wholesome Goods",
    useCase: "Stand up 13 EU regional storefronts on one shared translation pipeline.",
    goLive: "Phased · aligned to Feb 2027 renewal",
    contentPath: "Document & text", maturity: "mature", delivery: "connected", connector: "Sitecore",
    reviewModel: "internal",          // "regional marketing leads review"
    specialization: "Retail & e-commerce",
    industry: "Consumer goods",
    fde: "Gagan Reddy", segment: "EMEA Enterprise",
    team: ["sam", "jackie", "paul"],
    updated: "Jul 22", stage: "uat", stageProgress: 0.5,
    startDate: "2026-04-06", goLiveDate: "2026-09-30", lastActivityDate: "2026-07-22", ownerName: "Samantha",
    health: [78, 46, 64, 12, 71, 74],
    dueDates: { quality: "2026-07-28", accept: "2026-08-14" },
    nudge: "Eleven of thirteen regions have passed a real end-to-end run. Before go-live, the two remaining regions need reviewers assigned — and reviewer-agent usage is the one health metric still short of target.",
    notes: {
      goals: "One pipeline for 13 EU regions instead of per-region vendors.",
      langs: "en-GB source into 13 EU locales.",
      assets: "TMX consolidated from three prior vendors.",
      who: "Samantha Ford owns the program; regional marketing leads review.",
      quality: "Two regions still without named reviewers.",
    },
  },
  {
    id: "stepstone",
    customer: "StepStone",
    org: "StepStone",
    useCase: "Give recruiting teams a self-serve path for job content instead of a ticket queue.",
    goLive: "Sept 2026 target",
    contentPath: "Document & text", maturity: "mature",
    reviewModel: "internal",
    specialization: "HR & training",
    industry: "Recruitment",
    fde: "Gagan Reddy", segment: "EMEA Enterprise",
    team: ["kelli", "jackie"],
    updated: "Jul 19", stage: "setup", stageProgress: 0.6,
    startDate: "2026-06-15", goLiveDate: "2026-09-30", lastActivityDate: "2026-07-19", ownerName: "Kelli",
    health: [34, 18, 40, 0, 22, 55],
    dueDates: { templates: "2026-08-07", users: "2026-08-21" },
    nudge: "Workspace is provisioned and templates are half-built. The fastest unlock is the assignment template for recruiter self-serve — everything downstream in the core path waits on it.",
    notes: {
      goals: "Remove the central localization ticket queue.",
      langs: "de-DE source into nl-NL, fr-FR, pl-PL, en-GB.",
      who: "Kelli Hardacker sponsors; recruiting ops will administer.",
    },
  },
  {
    id: "sbd",
    customer: "Stanley Black & Decker",
    org: "Stanley Black & Decker",
    useCase: "Localize product training video for 18 regional workspaces on a shared template.",
    goLive: "Live since Jun 2026",
    contentPath: "Video & audio", maturity: "mature",
    fde: "Gagan Reddy", segment: "Global Enterprise",
    team: ["jackie", "paul", "james"],
    updated: "Jun 28", stage: "hyper", stageProgress: 1,
    startDate: "2026-03-02", goLiveDate: "2026-06-15", lastActivityDate: "2026-06-28", ownerName: "Jackie",
    health: [85, 52, 94, 38, 91, 83],
    nudge: "All 18 workspaces are live on the shared template. Subtitle turnaround is the metric worth quoting in the renewal conversation.",
    notes: {
      goals: "One template, 18 workspaces, no per-region rebuild.",
      langs: "en-US source into 11 locales with subtitles and dubbing.",
      who: "~150 trained across 18 workspaces.",
    },
  },
];

/* ────────────────────────────────────────────────────────────
   Journey assembly
   ──────────────────────────────────────────────────────────── */
